events/muzzle_cofM16.txt
events/muzzle_cofMP5.txt
events/muzzle_cofSG.txt
models/cof/ak74/mag.mdl
models/cof/ak74/mag_e.mdl
models/cof/ak74/plr.mdl
models/cof/ak74/vwm.mdl
models/cof/ak74/wrd.mdl
models/cof/anaconda/mag.mdl
models/cof/anaconda/mag_e.mdl
models/cof/anaconda/plr.mdl
models/cof/anaconda/plr_g.mdl
models/cof/anaconda/vwm.mdl
models/cof/anaconda/vwm_g.mdl
models/cof/anaconda/wrd.mdl
models/cof/anaconda/wrd_g.mdl
models/cof/axe/vwm.mdl
models/cof/axe/wld.mdl
models/cof/benelli/plr.mdl
models/cof/benelli/vwm.mdl
models/cof/benelli/wrd.mdl
models/cof/beretta/mag.mdl
models/cof/beretta/mag_e.mdl
models/cof/beretta/plr.mdl
models/cof/beretta/vwm.mdl
models/cof/beretta/wrd.mdl
models/cof/book/vwm.mdl
models/cof/book/wld.mdl
models/cof/branch/vwm.mdl
models/cof/branch/wld.mdl
models/cof/camera/vwm.mdl
models/cof/camera/wld.mdl
models/cof/deagle/mag.mdl
models/cof/deagle/mag_e.mdl
models/cof/deagle/vwm.mdl
models/cof/deagle/wld.mdl
models/cof/famas/mag.mdl
models/cof/famas/mag_e.mdl
models/cof/famas/plr.mdl
models/cof/famas/vwm.mdl
models/cof/famas/wrd.mdl
models/cof/g43/mag.mdl
models/cof/g43/mag_e.mdl
models/cof/g43/plr.mdl
models/cof/g43/vwm.mdl
models/cof/g43/wrd.mdl
models/cof/glock/mag.mdl
models/cof/glock/mag_e.mdl
models/cof/glock/plr.mdl
models/cof/glock/vwm.mdl
models/cof/glock/wrd.mdl
models/cof/glock18/mag.mdl
models/cof/glock18/mag_e.mdl
models/cof/glock18/plr.mdl
models/cof/glock18/vwm.mdl
models/cof/glock18/wrd.mdl
models/cof/hammer/vwm.mdl
models/cof/hammer/wld.mdl
models/cof/knife/vwm.mdl
models/cof/knife/wld.mdl
models/cof/l85/mag.mdl
models/cof/l85/mag_e.mdl
models/cof/l85/plr.mdl
models/cof/l85/vwm.mdl
models/cof/l85/wrd.mdl
models/cof/lantern/vwm.mdl
models/cof/lantern/wld.mdl
models/cof/m16/mag.mdl
models/cof/m16/mag_e.mdl
models/cof/m16/plr.mdl
models/cof/m16/vwm.mdl
models/cof/m16/wrd.mdl
models/cof/m76/mag.mdl
models/cof/m76/mag_e.mdl
models/cof/m76/plr.mdl
models/cof/m76/vwm.mdl
models/cof/m76/wrd.mdl
models/cof/mp5/mag.mdl
models/cof/mp5/mag_e.mdl
models/cof/mp5/plr.mdl
models/cof/mp5/vwm.mdl
models/cof/mp5/wrd.mdl
models/cof/mp5k/mag.mdl
models/cof/mp5k/mag_e.mdl
models/cof/mp5k/plr.mdl
models/cof/mp5k/vwm.mdl
models/cof/mp5k/wrd.mdl
models/cof/nstick/vwm.mdl
models/cof/nstick/wld.mdl
models/cof/p228/mag.mdl
models/cof/p228/mag_e.mdl
models/cof/p228/plr.mdl
models/cof/p228/vwm.mdl
models/cof/p228/wrd.mdl
models/cof/p345/mag.mdl
models/cof/p345/mag_e.mdl
models/cof/p345/plr.mdl
models/cof/p345/vwm.mdl
models/cof/p345/wrd.mdl
models/cof/revolver/box.mdl
models/cof/revolver/plr.mdl
models/cof/revolver/vwm.mdl
models/cof/revolver/wrd.mdl
models/cof/rifle/box.mdl
models/cof/rifle/plr.mdl
models/cof/rifle/scp.mdl
models/cof/rifle/vwm.mdl
models/cof/rifle/wrd.mdl
models/cof/sblade/vwm.mdl
models/cof/sblade/wld.mdl
models/cof/shells/12g.mdl
models/cof/shells/303.mdl
models/cof/shells/38.mdl
models/cof/shells/454c.mdl
models/cof/shells/454c_g.mdl
models/cof/shells/45acp.mdl
models/cof/shells/50ae.mdl
models/cof/shells/545mm.mdl
models/cof/shells/556.mdl
models/cof/shells/792.mdl
models/cof/shells/9mm.mdl
models/cof/shotgun/box.mdl
models/cof/shotgun/plr.mdl
models/cof/shotgun/vwm.mdl
models/cof/shotgun/wrd.mdl
models/cof/sledge/vwm.mdl
models/cof/sledge/wld.mdl
models/cof/spear/vwm.mdl
models/cof/spear/wld.mdl
models/cof/syringe/vwm.mdl
models/cof/syringe/wld.mdl
models/cof/tmp/mag.mdl
models/cof/tmp/mag_e.mdl
models/cof/tmp/plr.mdl
models/cof/tmp/vwm.mdl
models/cof/tmp/wrd.mdl
models/cof/uzi/mag.mdl
models/cof/uzi/mag_e.mdl
models/cof/uzi/plr.mdl
models/cof/uzi/vwm.mdl
models/cof/uzi/wrd.mdl
models/cof/v_actions.mdl
models/cof/vp70/mag.mdl
models/cof/vp70/mag_e.mdl
models/cof/vp70/plr.mdl
models/cof/vp70/vwm.mdl
models/cof/vp70/wrd.mdl
sound/cof/guns/ak74/bltback.ogg
sound/cof/guns/ak74/bltrel.ogg
sound/cof/guns/ak74/empty.ogg
sound/cof/guns/ak74/magin.ogg
sound/cof/guns/ak74/magout.ogg
sound/cof/guns/ak74/magout_r.ogg
sound/cof/guns/ak74/magrel.ogg
sound/cof/guns/ak74/safe.ogg
sound/cof/guns/ak74/shoot.ogg
sound/cof/guns/ak74/stock.ogg
sound/cof/guns/anaconda/close.ogg
sound/cof/guns/anaconda/cock.ogg
sound/cof/guns/anaconda/dump.ogg
sound/cof/guns/anaconda/empty.ogg
sound/cof/guns/anaconda/open.ogg
sound/cof/guns/anaconda/shoot.ogg
sound/cof/guns/anaconda/speed.ogg
sound/cof/guns/axe/hitb.ogg
sound/cof/guns/axe/hitw.ogg
sound/cof/guns/axe/swing.ogg
sound/cof/guns/benelli/empty.ogg
sound/cof/guns/benelli/insert.ogg
sound/cof/guns/benelli/pmpback.ogg
sound/cof/guns/benelli/pmpfwrd.ogg
sound/cof/guns/benelli/shoot.ogg
sound/cof/guns/benelli/sinsert.ogg
sound/cof/guns/beretta/empty.ogg
sound/cof/guns/beretta/maghit.ogg
sound/cof/guns/beretta/magin.ogg
sound/cof/guns/beretta/magout.ogg
sound/cof/guns/beretta/magrel.ogg
sound/cof/guns/beretta/shoot.ogg
sound/cof/guns/beretta/sldback.ogg
sound/cof/guns/beretta/sldrel.ogg
sound/cof/guns/book/burn.ogg
sound/cof/guns/book/end.ogg
sound/cof/guns/book/start.ogg
sound/cof/guns/branch/hit.ogg
sound/cof/guns/branch/swing.ogg
sound/cof/guns/camera/charge.ogg
sound/cof/guns/camera/lever.ogg
sound/cof/guns/camera/photo.ogg
sound/cof/guns/deagle/empty.ogg
sound/cof/guns/deagle/magin.ogg
sound/cof/guns/deagle/magout.ogg
sound/cof/guns/deagle/magout_e.ogg
sound/cof/guns/deagle/shoot.ogg
sound/cof/guns/deagle/sldrel.ogg
sound/cof/guns/famas/bltrel.ogg
sound/cof/guns/famas/magin.ogg
sound/cof/guns/famas/magout.ogg
sound/cof/guns/famas/shoot.ogg
sound/cof/guns/foley1.ogg
sound/cof/guns/foley2.ogg
sound/cof/guns/foley3.ogg
sound/cof/guns/g43/bltrel.ogg
sound/cof/guns/g43/magin.ogg
sound/cof/guns/g43/magout.ogg
sound/cof/guns/g43/shoot.ogg
sound/cof/guns/glock/maghit.ogg
sound/cof/guns/glock/magin.ogg
sound/cof/guns/glock/magout.ogg
sound/cof/guns/glock/rack.ogg
sound/cof/guns/glock/shoot.ogg
sound/cof/guns/glock/slide.ogg
sound/cof/guns/glock/switch.ogg
sound/cof/guns/glock18/magin.ogg
sound/cof/guns/glock18/magout.ogg
sound/cof/guns/glock18/magout_e.ogg
sound/cof/guns/glock18/rof.ogg
sound/cof/guns/glock18/shoot.ogg
sound/cof/guns/glock18/sldrel.ogg
sound/cof/guns/hammer/hit1.ogg
sound/cof/guns/hammer/hit2.ogg
sound/cof/guns/hammer/swing.ogg
sound/cof/guns/knife/hitb1.ogg
sound/cof/guns/knife/hitb2.ogg
sound/cof/guns/knife/hitb3.ogg
sound/cof/guns/knife/hitb4.ogg
sound/cof/guns/knife/hitw1.ogg
sound/cof/guns/knife/hitw2.ogg
sound/cof/guns/knife/hitw3.ogg
sound/cof/guns/knife/hitw4.ogg
sound/cof/guns/l85/bltback.ogg
sound/cof/guns/l85/bltrel.ogg
sound/cof/guns/l85/hit.ogg
sound/cof/guns/l85/magin.ogg
sound/cof/guns/l85/magout.ogg
sound/cof/guns/l85/magrel.ogg
sound/cof/guns/l85/rof.ogg
sound/cof/guns/l85/shoot.ogg
sound/cof/guns/m16/bltback.ogg
sound/cof/guns/m16/bltfwrd.ogg
sound/cof/guns/m16/magin.ogg
sound/cof/guns/m16/magout.ogg
sound/cof/guns/m16/magtap.ogg
sound/cof/guns/m16/shoot.ogg
sound/cof/guns/m16/switch.ogg
sound/cof/guns/m76/bltback.ogg
sound/cof/guns/m76/bltrel.ogg
sound/cof/guns/m76/magin.ogg
sound/cof/guns/m76/magout.ogg
sound/cof/guns/m76/shoot.ogg
sound/cof/guns/m_hit.ogg
sound/cof/guns/m_swing.ogg
sound/cof/guns/mp5/bltback.ogg
sound/cof/guns/mp5/bltfwrd.ogg
sound/cof/guns/mp5/magin.ogg
sound/cof/guns/mp5/magout.ogg
sound/cof/guns/mp5/shoot_end.ogg
sound/cof/guns/mp5/shoot_loop.ogg
sound/cof/guns/mp5k/bltback.ogg
sound/cof/guns/mp5k/bltlock.ogg
sound/cof/guns/mp5k/bltrel.ogg
sound/cof/guns/mp5k/magin.ogg
sound/cof/guns/mp5k/magout.ogg
sound/cof/guns/mp5k/magrel.ogg
sound/cof/guns/mp5k/shoot.ogg
sound/cof/guns/nstick/hitb1.ogg
sound/cof/guns/nstick/hitb2.ogg
sound/cof/guns/nstick/hitw1.ogg
sound/cof/guns/nstick/hitw2.ogg
sound/cof/guns/nstick/swing.ogg
sound/cof/guns/p228/magin.ogg
sound/cof/guns/p228/magin_p.ogg
sound/cof/guns/p228/magout.ogg
sound/cof/guns/p228/magout_e.ogg
sound/cof/guns/p228/shoot.ogg
sound/cof/guns/p228/sldback.ogg
sound/cof/guns/p228/sldfwrd.ogg
sound/cof/guns/p345/empty.ogg
sound/cof/guns/p345/magin.ogg
sound/cof/guns/p345/magout.ogg
sound/cof/guns/p345/shoot.ogg
sound/cof/guns/p345/slide.ogg
sound/cof/guns/p_smack.ogg
sound/cof/guns/p_swing2.ogg
sound/cof/guns/revolver/close.ogg
sound/cof/guns/revolver/empty.ogg
sound/cof/guns/revolver/insert.ogg
sound/cof/guns/revolver/open.ogg
sound/cof/guns/revolver/shell.ogg
sound/cof/guns/revolver/shoot.ogg
sound/cof/guns/rifle/bltback.ogg
sound/cof/guns/rifle/bltfwrd.ogg
sound/cof/guns/rifle/insert.ogg
sound/cof/guns/rifle/shoot.ogg
sound/cof/guns/sblade/draw.ogg
sound/cof/guns/sblade/draw2.ogg
sound/cof/guns/sblade/hitb1.ogg
sound/cof/guns/sblade/hitb2.ogg
sound/cof/guns/sblade/hitw1.ogg
sound/cof/guns/sblade/hitw2.ogg
sound/cof/guns/sblade/swing.ogg
sound/cof/guns/shotgun/insert.ogg
sound/cof/guns/shotgun/pmpback.ogg
sound/cof/guns/shotgun/pmpfwrd.ogg
sound/cof/guns/shotgun/pmpseq.ogg
sound/cof/guns/shotgun/shoot.ogg
sound/cof/guns/sledge/grab.ogg
sound/cof/guns/sledge/hitb.ogg
sound/cof/guns/sledge/hitw.ogg
sound/cof/guns/sledge/swing.ogg
sound/cof/guns/spear/electrocute.ogg
sound/cof/guns/spear/hitb.ogg
sound/cof/guns/spear/hitw.ogg
sound/cof/guns/spear/swing.ogg
sound/cof/guns/syringe/inject.ogg
sound/cof/guns/syringe/insert.ogg
sound/cof/guns/syringe/miss.ogg
sound/cof/guns/syringe/sleeve.ogg
sound/cof/guns/tmp/bltback.ogg
sound/cof/guns/tmp/bltfwrd.ogg
sound/cof/guns/tmp/magin.ogg
sound/cof/guns/tmp/magout.ogg
sound/cof/guns/tmp/shoot_end.ogg
sound/cof/guns/tmp/shoot_loop.ogg
sound/cof/guns/tmp/stock.ogg
sound/cof/guns/uzi/bltback.ogg
sound/cof/guns/uzi/bltfwrd.ogg
sound/cof/guns/uzi/magin.ogg
sound/cof/guns/uzi/magin_p.ogg
sound/cof/guns/uzi/magout.ogg
sound/cof/guns/uzi/magout_e.ogg
sound/cof/guns/uzi/magrel.ogg
sound/cof/guns/uzi/shoot.ogg
sound/cof/guns/uzi/stock.ogg
sound/cof/guns/vp70/magin.ogg
sound/cof/guns/vp70/magout.ogg
sound/cof/guns/vp70/shoot.ogg
sound/cof/guns/vp70/sldrel.ogg
sound/cof/guns/wpn_empty.ogg
sound/cof/items/itemget.ogg
sound/cof/items/weapget.ogg
sprites/cof/arifle/weapon_cofak74.txt
sprites/cof/arifle/weapon_coffamas.txt
sprites/cof/arifle/weapon_cofl85.txt
sprites/cof/arifle/weapon_cofm16.txt
sprites/cof/flame1.spr
sprites/cof/flame2.spr
sprites/cof/flame3.spr
sprites/cof/flame4.spr
sprites/cof/flame5.spr
sprites/cof/laserdot.spr
sprites/cof/melee/weapon_cofaxe.txt
sprites/cof/melee/weapon_cofbranch.txt
sprites/cof/melee/weapon_cofhammer.txt
sprites/cof/melee/weapon_cofknife.txt
sprites/cof/melee/weapon_cofnightstick.txt
sprites/cof/melee/weapon_cofsledgehammer.txt
sprites/cof/melee/weapon_cofspear.txt
sprites/cof/melee/weapon_cofswitchblade.txt
sprites/cof/pistol/weapon_cofberetta.txt
sprites/cof/pistol/weapon_cofdeagle.txt
sprites/cof/pistol/weapon_cofglock.txt
sprites/cof/pistol/weapon_cofglock18.txt
sprites/cof/pistol/weapon_cofp228.txt
sprites/cof/pistol/weapon_cofp345.txt
sprites/cof/pistol/weapon_cofvp70.txt
sprites/cof/revolver/weapon_cofanaconda.txt
sprites/cof/revolver/weapon_cofrevolver.txt
sprites/cof/rifle/weapon_cofg43.txt
sprites/cof/rifle/weapon_cofrifle.txt
sprites/cof/rof.spr
sprites/cof/shotgun/weapon_cofbenelli.txt
sprites/cof/shotgun/weapon_cofshotgun.txt
sprites/cof/smg/weapon_cofm76.txt
sprites/cof/smg/weapon_cofmp5.txt
sprites/cof/smg/weapon_cofmp5k.txt
sprites/cof/smg/weapon_coftmp.txt
sprites/cof/smg/weapon_cofuzi.txt
sprites/cof/special/ammo_syringe.spr
sprites/cof/special/weapon_cofbooklaser.txt
sprites/cof/special/weapon_cofcamera.txt
sprites/cof/special/weapon_cofgolden.txt
sprites/cof/special/weapon_coflantern.txt
sprites/cof/special/weapon_cofsyringe.txt
sprites/cof/v_action.txt
sprites/cof/wpn_sel01.spr
sprites/cof/wpn_sel02.spr
sprites/cof/wpn_sel03.spr
